server:
  port: 8999
spring:
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/JavaDesign?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    password: lbw
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true